[root][12:29:17 PM][INFO]: Server startup initialized
[root][12:29:17 PM][INFO]: Opening server at "localhost" with the port 19391
[root][12:29:17 PM][INFO]: Server is online
[websockets.server][12:29:22 PM][INFO]: connection open
[websockets.server][12:29:22 PM][INFO]: ('127.0.0.1', 54734)
[websockets.server][12:29:22 PM][ERROR]: connection handler failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/sync/server.py", line 498, in conn_handler
    handler(connection)
  File "/Users/marklopezjr./Desktop/Python projects/Websocket Computer Management System/Server/server.py", line 34, in handler
    username = json.loads(websocket.recv())
                          ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/sync/connection.py", line 198, in recv
    raise self.protocol.close_exc from self.recv_events_exc
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
